export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AFTER_LOGIN = 'AFTER_LOGIN';

export const LOGIN_ERROR = 'LOGIN_ERROR';

